package com.example.aguadeoromanagement.models

data class Inventory(
    var inventoryCode: String = "",
    val catalogCode: String = "",
    var code: String = "",
    var mark: String = "",
    var category: String = "",
    var description: String = "",
    var width: String = "",
    var height: String = "",
    var material: String = "",
    var color: String = "",
    var weight: String = "",
    var size: String = "",
    var stone: String = "",
    var stoneQuantity: String = "",
    var stoneType: String = "",
    var stoneSize: String = "",
    var carat: String = "",
    var stoneColor: String = "",
    var stoneClarity: String = "",
    var stoneCut: String = "",
    var stonePolish: String = "",
    var stoneSymmetry: String = "",
    var LAB: String = "",
    var certificate: String = "",
    var cost: String = "",
    var price: String = "0",
    var remark: String = "",
    var imageUrl: String = "",
    var status: String = "",
    var line: String = "",
    var collection: String = "",
    var style: String = "",
    var shape: String = "",
    var setting: String = "",
    var name: String = "",
    var ringPrize: String = "0",
    var meleePrize: String = "0",
    var stonePrize: String = "0",
    var orderInstructions: String = "",
    var prRing: String = "0",
    var prMelee: String = "0",
    var prStone: String = "0",
    var onWebsite: Boolean = false,
    var calculatedPrice: String = "",


    var rfidTag: String = "",
    var idLocation: String = ""
)
